### PR TITLE
[import label] change `_imports` suffix with `import_` prefix

### PR DESCRIPTION
**Pull request by israpps**
Allows to keep all the labeled imports together on the left panel due to alphabetic ordering

Still needs testing

### CODE REVIEW

**Comment by israpps** [comment]
Works like you can see on the PR
image

seems like arcade SYSMEM has more exports?

**Comment by Ziemas** [comment]
Huh, shouldn't sysmem 14 be Kprintf? It's in the list. Am I missing something?

**Comment by Ziemas** [comment]
Ooh, you modified `nameString` but that's also used to look up the function name in the list file. So now it won't find anything.

**Comment by israpps** [comment]
Sorry. Didn't read much, and mu java experience is literally 0

**Comment by israpps** [comment]
Is it possible to do the concatenation in place?

**Comment by Ziemas** [comment]
I don't really know Java either tbh. I'm sure it somehow must be though.

**Comment by israpps** [comment]
now it seems to be working!

PLease squash and merge this mess when u decide to merge

image

**Pull request merged**
